### ISSUE TITLE
Inconsistent pinout, J16, 5A-75E V6.0

### ISSUE THREAD

**Issue by rinatzakirov** [q3k/chubby75#101]
On the 5A-75E V6.0 board J16 has an inconsistent FPGA assignment.
HUB75 pins 1 and 6 are both assigned to FPGA Pin F14.
This is likely a typo.

**Comment by rinatzakirov** [comment]
Just confirmed that Pin 6 of J16 is connected to F14, and Pin 1 is something else.

**Comment by rinatzakirov** [comment]
Figured it out:
J16, Pin 1 is G14

So the fix is to change 
F14, 1, R0
to:
G14, 1, R0



FPGA Pin | HUB75 Pin | Function
-- | -- | --
F14 | 1 | R0
G13 | 2 | G0
F12 | 3 | B0
F13 | 5 | R1
F14 | 6 | G1
E14 | 7 | B1



FPGA Pin | HUB75 Pin | Function
-- | -- | --
F14 | 1 | R0
G13 | 2 | G0
F12 | 3 | B0
F13 | 5 | R1
F14 | 6 | G1
E14 | 7 | B1

**Comment by rinatzakirov** [comment]
Merge request created, along with a few more, hopefully useful, additions.
https://github.com/q3k/chubby75/pull/102

**Comment by kubabuda** [comment]
PR is merged, perhaps issue can be closed?

**Comment by tomverbeure** [comment]
Closing.
