### ISSUE TITLE
Blew up my first 5A-75E... what could have gone wrong?

### ISSUE THREAD

**Issue by dixi83** [q3k/chubby75#111]
Hi All,
My first attempt replacing the buffers with the 74LVC245 failed... after replacing them the CPU gets really hot and does not respond any more to anything.... so I guess I fried it.

![5A-75E board](https://user-images.githubusercontent.com/10693808/232571556-cec2d6da-6cd6-4a5b-866a-69e0aaee6500.png)

The idea was to make the J1-J8 input and leave the J9-J16 output
I don't know what went wrong, I tested every IC after replacing for short circuit and between every pin.
There are 3 options I see:

- my multimeter fried something while testing
- the new 74LVC245 came from china and they are b/c/d (or maybe z) -stock
- The PCB is a 4 or more layer PCB and I cut to much

I ordered a new one but I don't want to fry my new one.

Thanks!

**Comment by dixi83** [comment]
The version I have is a 8.2. As far as I could determine it has the same pin assignment as documented for the 7.1. I have only tested the RGB pins not A-E...

**Comment by kittennbfive** [comment]
Hi,

at least on my board which is V7.0 some FPGA-pins are connected to multiple output buffers. This could lead to some short-circuits if not taken care of. Just a thought. Also maybe the buffers are crap, i would recommand buying them from a reputable source like Mouser, Digikey, Newark/Element14/Farnell, ... depending on your location in the world.

I have a file !!!FOR VERSION 7.0!!! which shows what is connected where. Il will add it to my github, might be useful for other people.

Also i would suggest removing all the buffers with hot air and see if the FPGA (not CPU) works again.

**Comment by dixi83** [comment]
@kittennbfive thanks for your reply!
I ordered a new card from Ali and also some new IC's from Farnell. I will do a retry next week is I have more time. I will use kapton tape to isolate Pin 1 and 20 it looks really neat. I did not removed anything else then the buffers with a wire attached on the photo... what I do know now I should not have removed the buffers I wanted to keep as output. I did used a hot air gun. I only used a iron for cleaning the pads and some solder removal lint (not sure if it is the right English word)
Sorry for shouting "CPU" to a FPGA... I was not aware 🤣 

@everyoneelse this is the repo kittennbfive is talking about: https://github.com/kittennbfive/5A-75B-tools
I received my new card last week. I also ordered a mesa card to get started with my machine and getting used to the way of configuring LinuxCNC.

The thing I did not mentioned in my previous post is that I did not even test the card before changing anything. so another option would be that my first card was death on arrival...

**Comment by kittennbfive** [comment]
The word you are looking for is "solder wick". ;-)

As i said, you really (imho) should remove (or erase at least) the FLASH containing the default bitstream so there won't be any FPGA-pins fighting against the new installed buffers. Also you should check for FPGA-pins connected to multiple buffers for the same reason. I am afraid i can't give more details because i don't have a V8.

**Comment by dixi83** [comment]
Thanks for your comment and extra warning. I finally found what you meant: 
https://github.com/kittennbfive/5A-75B-tools/blob/8f4c14c88fb531b183f87d95d1defc01eb2f0712/I_want_inputs/README.md
The next question is a noob question ;-) ... 
Can I "remove" the flash by compiling "empty" firmware and load this using openFPGAloader or is there a way to do this in another easier way?

**Comment by kittennbfive** [comment]
I would guess that simply erasing the flash should be ok, but honestly i don't know for sure. :(
