### ISSUE TITLE
5A-75E v8.2

### ISSUE THREAD

**Issue by rthorntn** [q3k/chubby75#115]
Hi,

I’ve just acquired a few 5A-75E v8.2 boards. It’s not mentioned here, is it supported?

![PXL_20230807_070240762~2](https://github.com/q3k/chubby75/assets/12758977/25e728bb-4842-472b-a967-f0871dc6d9ec)

Thanks!

**Comment by Peter-van-Tol** [comment]
Yeah, the are supported! Just use the firmware voor the V6.0.

Checked my boards: they are V8.2 as well, confirmed to work 👍

**Comment by boilerbots** [comment]
I just got an 8.2 board and it would be helpful to figure out the JTAG connections so we can load the firmware.

**Comment by tomverbeure** [comment]
I've merged PR 114 with V8.2 specific info.
