### ISSUE TITLE
Can Huidu HD-R712 be supported?

### ISSUE THREAD

**Issue by kholia** [q3k/chubby75#123]
Hey Folks,

This card is widely available for a reasonable price. I am wondering if this board has a JTAG header available, and if the onboard FPGA is well supported by FOSS toolchains.

Thanks for the help!

![products-5_23_3](https://github.com/user-attachments/assets/6ecd0cbc-3421-4d77-985b-50bafb34559c)
![products-1_35](https://github.com/user-attachments/assets/708fe338-fbae-41b7-8bda-cec8d03d79ee)
![products-linsn_r712_-](https://github.com/user-attachments/assets/80b0b9a2-d03a-4c98-8473-8806fdf2d89a)
![products-2_32_6](https://github.com/user-attachments/assets/876e6fa5-bcb9-4f9b-90e3-880347325892)

Sample product URL: https://ledcontrollercard.com/product/huidu-hd-r712-led-display-full-color-receiving-card/

PS: I haven't bought one yet.

**Comment by tomverbeure** [comment]
The only way to know is to buy it and find out. It's not even clear what kind of FPGA is being used. At point, these receiving cards are so cheap that it may be better to just stick with what's already been done. Unless you want to do the reverse engineering for the sport, of course!

**Comment by kholia** [comment]
Roger @tomverbeure - thank you!

The availability of these 'Huidu' cards seems to be better than the well-supported Colorlight boards - at least here locally.

If I fail to source more Colorlight boards, I might be tempted to get one of these Huidu boards and struggle to make it work.

Let's see!

**Comment by kholia** [comment]
It seems Huidu R712 uses an [Anlogic](https://www.anlogic.com/en) FPGA and I failed at even downloading the required tool-chain as it is behind multiple layers of 'verification'.

**Comment by kholia** [comment]
I was able to source Colorlight boards locally! Yep - Sticking with Colorlight makes sense for now. Thanks!

**Comment by kholia** [comment]
I couldn't resist after all...

https://rfcorner.in/posts/reversing-huidu-fpga-board/ has my reversing notes.

CC @tomverbeure as well - thanks!
