### ISSUE TITLE
V8.2 PHY Pin mapping does not work

### ISSUE THREAD

**Issue by particlerain** [q3k/chubby75#124]
Hi,

i managed Ethernet  to work flawless on my 5A-75B v7 board, but with your hardware_V8.2.md pin mapping my 5A-75B V8.2  Ethernet does not work. 
Are you sure they are the correct pins for 8.2? Because your PHY mappings on v8  are the same as v8.2. 
Could please recheck that ? Or anybody have succesfully managed to work the ethernet on v8.2?
Thanks.

**Comment by tomverbeure** [comment]
The pin mapping that are listed here have been supplied by hobbyists who were happy to spend the effort of submitting a pull request. They haven't been double checked. It's definitely possible that there are errors in it. If you manage to figure out the issue, feel free to submit a fix.
