### ISSUE TITLE
better way to fix the JTAG!?

### ISSUE THREAD

**Issue by samsoniuk** [q3k/chubby75#21]
Hi colleagues,

I tested the mounting of the JTAG connector glued in the edge of the board, but I found that this configuration is not so "solid" from the mechanical point of view. Also, the JTAG connector in line requires use the color JTAG cable, which it needs to be wired pin by pin in the correct order. 

After some quick tests, I found that is possible use the 10-pin JP3 connector, in a way that the standard 14-pin flat cable found in the ultra-low-cost "xinglinx" JTAG adapter can be directly used:

![IMG_2181](https://user-images.githubusercontent.com/42520878/67364940-f6e17f80-f546-11e9-8e80-7e0d2af1e514.JPG)

Of course, although the pin numbers are labelled wrong (JTAG pin 1 connected to PCB pin 9, JTAG pin 2 connected to PCB pin 2, etc until all ten first pins are connected), the pin order from JP3 in the PCB is exactly the same as the first 10 pins from the 14-pin JTAG connector, which make it very quick and practical to connect:

VREF(9) TMS(7) TCK(5) TDO(3) TDI(1)
GND(10) NC(8) NC(6) **5V(4)** NC(2)

VREF(1) TMS(3) TCK(5) TDO(7) TDI(9) **NC(11) HALT(13)**
GND(2) GND(4) GND(6) GND(8) GND(10) **GND(12) GND(14)**

The NC pins are not connected in the PCB and can be connected to the JTAG GND, but the **5V(4)** is powered by the +5V in the PCB, which means that is better bender or cut this pin in a way that is not physically connected to the flat cable, in order to avoid a short circuit in the JTAG adapter between the GND and 5V!

![IMG_2251](https://user-images.githubusercontent.com/42520878/67367442-e1bb1f80-f54b-11e9-9c60-31e7c0ec53e0.JPG)

Well, in the other side of the board, the main advantages are that the JP3 is better fixed via a THT connector, the GND is already present i the pin 10 and the 3V3 can be routed from a better location:

![IMG_2183](https://user-images.githubusercontent.com/42520878/67365776-a5d28b00-f548-11e9-82ec-d9d2cced9f08.JPG)

Best regards,
Marcelo

**Comment by tomverbeure** [comment]
I think this is great!

Do you think you can convert these instructions into a separate documentation file and create a pull request?

Tom

**Comment by samsoniuk** [comment]
Here the proposed changes and updates:

https://github.com/darklife/chubby75/blob/master/rv901t/README.md
https://github.com/darklife/chubby75/blob/master/rv901t/doc/getting_started/improved_jtag_getting_started.md

**Comment by tomverbeure** [comment]
Changes applied. Closing.
