### ISSUE TITLE
Status of HUB75 support

### ISSUE THREAD

**Issue by NiklasFauth** [q3k/chubby75#23]
I was wondering if anyone already tried to stuck all these pieces of work together and managed to implement an eg. OPC sink to control HUB75 or WS2812 leds with this board.

If not, what work would be necessary?

- Niklas

**Comment by tomverbeure** [comment]
[Looks](https://twitter.com/FauthNiklas/status/1240066364557135873) like you made it work! :wink:

All that remains now is a detailed write-up so we add a link to it!
