### ISSUE TITLE
Is there a readme on how to get this project working?

### ISSUE THREAD

**Issue by PM1001** [q3k/chubby75#26]
I have been trying in vain to get this project working. It seems there is always an issue with the litex dependencies.

For instance, this is one of the problems I am having:
ImportError: No module named 'liteeth.phy.s6rgmii'

Can anybody give me a hint to how to install all the litex and migen components for this project? 

Thanks

**Comment by enjoy-digital** [comment]
You can install LiteX with:
````
$ wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
$ chmod +x litex_setup.py
$ ./litex_setup.py init install --user (--user to install to user directory)
````

**Comment by PM1001** [comment]
Thank you very much! That seems to have done the trick!
For some reason none of the permutations of the installations under third-party/ was working for me.

**Comment by NiklasFauth** [comment]
Some more documentation can also be found here:
https://github.com/NiklasFauth/colorlight-led-cube
