### ISSUE TITLE
Update README to indicate support for two cards now

### ISSUE THREAD

**Issue by mithro** [q3k/chubby75#35]
This repo seems to have grown support for multiple parts now;
 * RV901T LED "Receiver Card"
 * Colorlight 5A-75B

It would be good to update the README to reflect that (and maybe the directory structure too?).

It seems like there are other potential boards in this series that might be added in the future too? See #20

**Comment by tomverbeure** [comment]
I just updated the READMEs to reflect that there are multiple versions and boards.
