### ISSUE TITLE
different sdram on Colorlight 5A-75B V7.0 Hardware

### ISSUE THREAD

**Issue by dasdgw** [q3k/chubby75#46]
Hi,

I noticed that on my v7.0 hw there are 2 winbond (W9816G6JH-6) sdram chips instead of 2 ESMT M12L16161A-5T.
Besides from that my board looks exactly like the one on the pictures.

Should we add this to the documentation?

**Comment by tomverbeure** [comment]
WinBond is a popular generic replacement for DRAMs, so this is no surprise.

Feel free to add it to the documentation!

Tom

**Comment by tomverbeure** [comment]
Pull request #47 applied.
