### ISSUE TITLE
Pin 5 Connector J4 of Colorlight V7.0

### ISSUE THREAD

**Issue by NiklasFauth** [q3k/chubby75#52]
The FPGA Pin remains unknown. Too sad, I would have loved to use this port for my LED cube.
Does anyone know what this Pin connects to, or do I need to sacrifice a board to find out?

LG Niklas

**Comment by smunaut** [comment]
Try M9
Educated guess :)

**Comment by Disasm** [comment]
Yes, it's M9. Updated the table in https://github.com/q3k/chubby75/pull/60

**Comment by tomverbeure** [comment]
Closing.
