### ISSUE TITLE
LEDG & button ?

### ISSUE THREAD

**Issue by jeanthom** [q3k/chubby75#8]
I traced the schematic of the button next to JP2 and S1 :

![capture d ecran 2018-12-23 a 17 05 11](https://user-images.githubusercontent.com/25333063/50385377-f719b000-06d4-11e9-9a4a-72c4023bc405.png)

That schematic feels weird, maybe I've made a huge mistake ? What do you think ?

Also, I noticed that P4 from the FPGA isn't connected to the button but rather to U600:B7.

**Comment by q3k** [comment]
Here's my tracing of this region:

![image](
https://q3k.org/u/fe5c9d2b3bf746c0891d94e858186cb648acca66ed37a9848581f86389baa494.png)

**Comment by q3k** [comment]
The marking on Q503 is `1AM`, which points to a [MMBT3904LT1 NPN transistor by ONSemi](https://www.onsemi.com/pub/Collateral/MMBT3904LT1-D.PDF). Labeling BCE on the trace:

![image](https://q3k.org/u/5056d29d2335344b59682f493ed8c3096b01df2228cbbbcc03b69b83708d0ea5.png)

**Comment by q3k** [comment]
I've stared at this for a while, and it looks exactly like the schematic @jeanthom posted.

So yeah, that's a weird circuit. I assume Q503 is used as a diode here, maybe also to limit C->E current drained by the button or when JP2.2 is tied low? I assume there's some factory use of JP2 (it's one of the few populated connectors) where this whole mess make sense.

I don't think we can actually read the button state via F7...

**Comment by q3k** [comment]
Correction: we probably can read the button if we just set F7 as a high-impedance input - pressing the button then will cause F7 to go to 0Vish via Q503. When the button is not pressed, F7 is at around 2.8V.

**Comment by q3k** [comment]
Documented in https://github.com/q3k/chubby75/commit/9f0e47c58e9b4f4853c8e42d5072594c361b15b8
