### ISSUE TITLE
Serial pins preference?

### ISSUE THREAD

**Issue by enjoy-digital** [q3k/chubby75#9]
I can prepare a design with a CPU and SDRAM but it would be good to define the I/Os we want to use for serial. Do you have any preference?

**Comment by jeanthom** [comment]
![capture d ecran 2018-12-24 a 13 09 42](https://user-images.githubusercontent.com/25333063/50399102-3c91b800-077d-11e9-9592-e73a03d22342.png)

I think we could use some of the I/Os that are accessible through JP4.

**Comment by enjoy-digital** [comment]
Thanks, yes we could use these pins.

**Comment by enjoy-digital** [comment]
We can use pin 3/5 of JP4. (validated in https://github.com/q3k/chubby75/pull/11)

**Comment by q3k** [comment]
Yep, let's use JP4.3 and JP4.5. I've marked that in our documentation.
