### ISSUE TITLE
Add link with some 5a-75b hacking

### ISSUE THREAD

**Issue by eibach** [q3k/chubby75#95]
In https://zeromips.org/posts/2022-05-29-5a-75b I have documented my modification of the 5a-75b board. I suppose this could be helpful/encouraging for others. As this github repo is the de facto standard documentation, maybe you could add a link to my post here.

**Comment by q3k** [comment]
I'll gladly add a link, but would you kindly file a PR? :)

**Comment by eibach** [comment]
Thanks, done.

**Comment by q3k** [comment]
Thank you!
